require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/borrowings", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Borrowing. As you add validations to Borrowing, be sure to
  # adjust the attributes here as well.
  let(:book) { Book.create!(title: "Test Book", author: "Test Author") }
  let(:reader) { Reader.create!(name: "Test Reader", email: "reader@example.com") }

  let(:valid_attributes) {
    { book_id: book.id, reader_id: reader.id, borrow_date: Date.today }
  }

  let(:invalid_attributes) {
    { book_id: nil, reader_id: nil, borrow_date: nil }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # BorrowingsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Borrowing.create! valid_attributes
      get borrowings_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      borrowing = Borrowing.create! valid_attributes
      get borrowing_url(borrowing), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Borrowing" do
        expect {
          post borrowings_url,
               params: { borrowing: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Borrowing, :count).by(1)
      end

      it "renders a JSON response with the new borrowing" do
        post borrowings_url,
             params: { borrowing: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Borrowing" do
        expect {
          post borrowings_url,
               params: { borrowing: invalid_attributes }, as: :json
        }.to change(Borrowing, :count).by(0)
      end

      it "renders a JSON response with errors for the new borrowing" do
        post borrowings_url,
             params: { borrowing: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { return_date: Date.today + 7.days }
      }

      it "updates the requested borrowing" do
        borrowing = Borrowing.create! valid_attributes
        patch borrowing_url(borrowing),
              params: { borrowing: new_attributes }, headers: valid_headers, as: :json
        borrowing.reload
        expect(borrowing.return_date).to eq(Date.today + 7.days)
      end

      it "renders a JSON response with the borrowing" do
        borrowing = Borrowing.create! valid_attributes
        patch borrowing_url(borrowing),
              params: { borrowing: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the borrowing" do
        borrowing = Borrowing.create! valid_attributes
        patch borrowing_url(borrowing),
              params: { borrowing: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested borrowing" do
      borrowing = Borrowing.create! valid_attributes
      expect {
        delete borrowing_url(borrowing), headers: valid_headers, as: :json
      }.to change(Borrowing, :count).by(-1)
    end
  end
end
